### ISSUE TITLE
CI Reliability 2023-02

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite-compat#2]
https://github.com/toeverything/blocksuite/actions/runs/4179621354/jobs/7239774989
https://github.com/toeverything/AFFiNE/actions/runs/4180851534/jobs/7242251474

---

### https://github.com/toeverything/blocksuite/pull/1199
https://github.com/toeverything/blocksuite/actions/runs/4187078414/jobs/7256480644
https://github.com/toeverything/blocksuite/actions/runs/4187078414/jobs/7256510420

---

https://github.com/toeverything/blocksuite/actions/runs/4187882162/jobs/7258327786

---

### https://github.com/toeverything/blocksuite/pull/1210
https://github.com/toeverything/blocksuite/actions/runs/4189603135/jobs/7262116096

---

### https://github.com/toeverything/AFFiNE/pull/1037

https://github.com/toeverything/AFFiNE/actions/runs/4189591773/jobs/7262122869
https://github.com/toeverything/AFFiNE/actions/runs/4189591773/jobs/7262164885
https://github.com/toeverything/AFFiNE/actions/runs/4189591773/jobs/7262183314

**Comment by himself65** [comment]
### https://github.com/toeverything/blocksuite/pull/1240

https://github.com/toeverything/blocksuite/actions/runs/4192774284/jobs/7268796485

**Comment by himself65** [comment]
### https://github.com/toeverything/blocksuite/pull/1252

https://github.com/toeverything/blocksuite/actions/runs/4200203325/jobs/7285975989

**Comment by himself65** [comment]
### https://github.com/toeverything/AFFiNE/pull/1078

https://github.com/toeverything/AFFiNE/actions/runs/4200201412/jobs/7285971841

**Comment by Himself65** [comment]
https://github.com/toeverything/blocksuite-compat/issues/2

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/actions/runs/4200244452/jobs/7286066215

**Comment by himself65** [comment]
### https://github.com/toeverything/AFFiNE/pull/1103

https://github.com/toeverything/AFFiNE/actions/runs/4208887551/jobs/7305705297

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/actions/runs/4215047666/jobs/7315911298

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/actions/runs/4215037407/jobs/7315894159

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/actions/runs/4215037407/jobs/7315894188

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/actions/runs/4215037407/jobs/7315894207
